image: gitpod/workspace-node

tasks:
  - init: nvm install && yarn install && yarn build
    command: PORT=3000 yarn start:server
  - init: docker pull gitpod/workspace-node
    command: exit
vscode:
  extensions:
    - dbaeumer.vscode-eslint
