image:
  file: .gitpod.Dockerfile

tasks:
  - init: nvm install && yarn
    command: PORT=3000 yarn start
  - init: docker pull gitpod/workspace-node
    command: exit
vscode:
  extensions:
    - dbaeumer.vscode-eslint
