name: Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-release:
    runs-on: ubuntu-latest
    name: Build and publish Docker image
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
    
      - name: Get the version from package.json
        id: package-version
        run: echo "{version}={$(jq -r .version package.json)}" >> $GITHUB_OUTPUT

      - name: Auth Google Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: |
            eu.gcr.io/gitpod-core-dev/build/ide/xterm-web:commit-${{ github.sha }}
            eu.gcr.io/gitpod-core-dev/build/ide/xterm-web:latest
          build-args: |
            XTERM_COMMIT=${{ github.sha }}
            XTERM_VERSION=${{ steps.package-version.outputs.version }}
